.phony:	all clean 

all:
	(cd 0 ; javac *.java)
	(cd 1 ; javac *.java)
	(cd 2 ; javac *.java)
	(cd 3 ; javac *.java)
	(cd 4 ; javac *.java)
	(cd 5 ; javac *.java)
	(cd 6 ; javac *.java)
	(cd 7 ; javac compiler/*.java *.java)
	(cd 8 ; javac compiler/*.java *.java)

clean	:
	find . -name '*.class' -exec rm {} \;

