/* The following code was generated by JFlex 1.4.2 on 11/4/09 8:11 PM */

// Based on the "simple example" in the JFlex manual:
// http://jflex.de/manual.html

/* JFlex example: part of Java language lexer specification */
//import java_cup.runtime.*;
//import compiler.*;

/**
 * This class is a simple example lexer.
 */



public class Lexer {

  /** This character denotes the end of file */
  public static final int YYEOF = -1;

  /** initial size of the lookahead buffer */
  private static final int ZZ_BUFFERSIZE = 16384;

  /** lexical states */
  public static final int STRING = 2;
  public static final int YYINITIAL = 0;

  /**
   * ZZ_LEXSTATE[l] is the state in the DFA for the lexical state l
   * ZZ_LEXSTATE[l+1] is the state in the DFA for the lexical state l
   *                  at the beginning of a line
   * l is of the form l = 2*k, k a non negative integer
   */
  private static final int ZZ_LEXSTATE[] = { 
     0,  0,  1, 1
  };

  /** 
   * Translates characters to character classes
   */
  private static final String ZZ_CMAP_PACKED = 
    "\11\10\1\3\1\2\1\0\1\3\1\1\16\10\4\0\1\3\1\34"+
    "\1\65\1\0\1\10\1\0\1\35\1\0\1\22\1\23\1\5\1\40"+
    "\1\27\1\41\1\30\1\4\1\21\1\12\1\11\1\16\1\13\1\20"+
    "\1\17\1\14\1\15\1\7\1\0\1\26\1\33\1\31\1\32\2\0"+
    "\32\6\1\0\1\66\1\0\1\37\1\10\1\0\1\46\1\42\1\50"+
    "\1\54\1\45\1\56\1\6\1\63\1\55\2\6\1\44\1\6\1\47"+
    "\1\43\1\62\1\6\1\60\1\51\1\53\1\61\1\64\1\57\1\52"+
    "\2\6\1\24\1\36\1\25\1\0\41\10\2\0\4\10\4\0\1\6"+
    "\2\0\1\10\7\0\1\6\4\0\1\6\5\0\27\6\1\0\37\6"+
    "\1\0\u013f\6\31\0\162\6\4\0\14\6\16\0\5\6\11\0\1\6"+
    "\21\0\130\10\5\0\23\10\12\0\1\6\13\0\1\6\1\0\3\6"+
    "\1\0\1\6\1\0\24\6\1\0\54\6\1\0\46\6\1\0\5\6"+
    "\4\0\202\6\1\0\4\10\3\0\105\6\1\0\46\6\2\0\2\6"+
    "\6\0\20\6\41\0\46\6\2\0\1\6\7\0\47\6\11\0\21\10"+
    "\1\0\27\10\1\0\3\10\1\0\1\10\1\0\2\10\1\0\1\10"+
    "\13\0\33\6\5\0\3\6\15\0\4\10\14\0\6\10\13\0\32\6"+
    "\5\0\13\6\16\10\7\0\12\10\4\0\2\6\1\10\143\6\1\0"+
    "\1\6\10\10\1\0\6\10\2\6\2\10\1\0\4\10\2\6\12\10"+
    "\3\6\2\0\1\6\17\0\1\10\1\6\1\10\36\6\33\10\2\0"+
    "\3\6\60\0\46\6\13\10\1\6\u014f\0\3\10\66\6\2\0\1\10"+
    "\1\6\20\10\2\0\1\6\4\10\3\0\12\6\2\10\2\0\12\10"+
    "\21\0\3\10\1\0\10\6\2\0\2\6\2\0\26\6\1\0\7\6"+
    "\1\0\1\6\3\0\4\6\2\0\1\10\1\6\7\10\2\0\2\10"+
    "\2\0\3\10\11\0\1\10\4\0\2\6\1\0\3\6\2\10\2\0"+
    "\12\10\2\6\2\10\15\0\3\10\1\0\6\6\4\0\2\6\2\0"+
    "\26\6\1\0\7\6\1\0\2\6\1\0\2\6\1\0\2\6\2\0"+
    "\1\10\1\0\5\10\4\0\2\10\2\0\3\10\13\0\4\6\1\0"+
    "\1\6\7\0\14\10\3\6\14\0\3\10\1\0\11\6\1\0\3\6"+
    "\1\0\26\6\1\0\7\6\1\0\2\6\1\0\5\6\2\0\1\10"+
    "\1\6\10\10\1\0\3\10\1\0\3\10\2\0\1\6\17\0\2\6"+
    "\2\10\2\0\12\10\1\0\1\10\17\0\3\10\1\0\10\6\2\0"+
    "\2\6\2\0\26\6\1\0\7\6\1\0\2\6\1\0\5\6\2\0"+
    "\1\10\1\6\6\10\3\0\2\10\2\0\3\10\10\0\2\10\4\0"+
    "\2\6\1\0\3\6\4\0\12\10\1\0\1\6\20\0\1\10\1\6"+
    "\1\0\6\6\3\0\3\6\1\0\4\6\3\0\2\6\1\0\1\6"+
    "\1\0\2\6\3\0\2\6\3\0\3\6\3\0\10\6\1\0\3\6"+
    "\4\0\5\10\3\0\3\10\1\0\4\10\11\0\1\10\17\0\11\10"+
    "\11\0\1\10\7\0\3\10\1\0\10\6\1\0\3\6\1\0\27\6"+
    "\1\0\12\6\1\0\5\6\4\0\7\10\1\0\3\10\1\0\4\10"+
    "\7\0\2\10\11\0\2\6\4\0\12\10\22\0\2\10\1\0\10\6"+
    "\1\0\3\6\1\0\27\6\1\0\12\6\1\0\5\6\2\0\1\10"+
    "\1\6\7\10\1\0\3\10\1\0\4\10\7\0\2\10\7\0\1\6"+
    "\1\0\2\6\4\0\12\10\22\0\2\10\1\0\10\6\1\0\3\6"+
    "\1\0\27\6\1\0\20\6\4\0\6\10\2\0\3\10\1\0\4\10"+
    "\11\0\1\10\10\0\2\6\4\0\12\10\22\0\2\10\1\0\22\6"+
    "\3\0\30\6\1\0\11\6\1\0\1\6\2\0\7\6\3\0\1\10"+
    "\4\0\6\10\1\0\1\10\1\0\10\10\22\0\2\10\15\0\60\6"+
    "\1\10\2\6\7\10\4\0\1\10\7\6\10\10\1\0\12\10\47\0"+
    "\2\6\1\0\1\6\2\0\2\6\1\0\1\6\2\0\1\6\6\0"+
    "\4\6\1\0\7\6\1\0\3\6\1\0\1\6\1\0\1\6\2\0"+
    "\2\6\1\0\4\6\1\10\2\6\6\10\1\0\2\10\1\6\2\0"+
    "\5\6\1\0\1\6\1\0\6\10\2\0\12\10\2\0\2\6\42\0"+
    "\1\6\27\0\2\10\6\0\12\10\13\0\1\10\1\0\1\10\1\0"+
    "\1\10\4\0\2\10\10\6\1\0\42\6\6\0\24\10\1\0\2\10"+
    "\4\6\4\0\10\10\1\0\44\10\11\0\1\10\71\0\42\6\1\0"+
    "\5\6\1\0\2\6\1\0\7\10\3\0\4\10\6\0\12\10\6\0"+
    "\6\6\4\10\106\0\46\6\12\0\51\6\7\0\132\6\5\0\104\6"+
    "\5\0\122\6\6\0\7\6\1\0\77\6\1\0\1\6\1\0\4\6"+
    "\2\0\7\6\1\0\1\6\1\0\4\6\2\0\47\6\1\0\1\6"+
    "\1\0\4\6\2\0\37\6\1\0\1\6\1\0\4\6\2\0\7\6"+
    "\1\0\1\6\1\0\4\6\2\0\7\6\1\0\7\6\1\0\27\6"+
    "\1\0\37\6\1\0\1\6\1\0\4\6\2\0\7\6\1\0\47\6"+
    "\1\0\23\6\16\0\11\10\56\0\125\6\14\0\u026c\6\2\0\10\6"+
    "\12\0\32\6\5\0\113\6\3\0\3\10\17\0\15\6\1\0\4\6"+
    "\3\10\13\0\22\6\3\10\13\0\22\6\2\10\14\0\15\6\1\0"+
    "\3\6\1\0\2\10\14\0\64\6\40\10\3\0\1\6\3\0\1\10"+
    "\1\6\1\10\2\0\12\10\41\0\3\10\2\0\12\10\6\0\130\6"+
    "\10\0\51\6\1\10\126\0\35\6\3\0\14\10\4\0\14\10\12\0"+
    "\12\10\36\6\2\0\5\6\u038b\0\154\6\224\0\234\6\4\0\132\6"+
    "\6\0\26\6\2\0\6\6\2\0\46\6\2\0\6\6\2\0\10\6"+
    "\1\0\1\6\1\0\1\6\1\0\1\6\1\0\37\6\2\0\65\6"+
    "\1\0\7\6\1\0\1\6\3\0\3\6\1\0\7\6\3\0\4\6"+
    "\2\0\6\6\4\0\15\6\5\0\3\6\1\0\7\6\17\0\4\10"+
    "\32\0\5\10\20\0\2\10\23\0\1\10\13\0\4\10\6\0\6\10"+
    "\1\0\1\6\15\0\1\6\40\0\22\10\36\0\15\10\4\0\1\10"+
    "\3\0\6\10\27\0\1\6\4\0\1\6\2\0\12\6\1\0\1\6"+
    "\3\0\5\6\6\0\1\6\1\0\1\6\1\0\1\6\1\0\4\6"+
    "\1\0\3\6\1\0\7\6\3\0\3\6\5\0\5\6\26\0\44\10"+
    "\u0e81\0\2\6\1\10\31\0\17\10\1\0\5\6\2\0\3\10\2\6"+
    "\4\0\126\6\2\0\2\10\2\0\3\6\1\0\132\6\1\10\4\6"+
    "\5\0\50\6\4\0\136\6\21\0\30\6\70\0\20\6\u0200\0\u19b6\6"+
    "\112\0\u51a6\6\132\0\u048d\6\u0773\0\u2ba4\6\u215c\0\u012e\6\2\0\73\6"+
    "\225\0\7\6\14\0\5\6\5\0\1\6\1\10\12\6\1\0\15\6"+
    "\1\0\5\6\1\0\1\6\1\0\2\6\1\0\2\6\1\0\154\6"+
    "\41\0\u016b\6\22\0\100\6\2\0\66\6\50\0\14\6\1\10\3\0"+
    "\20\10\20\0\4\10\17\0\2\10\30\0\3\10\31\0\1\10\6\0"+
    "\5\6\1\0\207\6\2\0\1\10\4\0\1\10\13\0\12\10\7\0"+
    "\32\6\4\0\1\10\1\0\32\6\12\0\1\10\131\6\3\0\6\6"+
    "\2\0\6\6\2\0\6\6\2\0\3\6\3\0\2\10\3\0\2\10"+
    "\22\0\3\10\4\0";

  /** 
   * Translates characters to character classes
   */
  private static final char [] ZZ_CMAP = zzUnpackCMap(ZZ_CMAP_PACKED);

  /** 
   * Translates DFA states to action switch labels.
   */
  private static final int [] ZZ_ACTION = zzUnpackAction();

  private static final String ZZ_ACTION_PACKED_0 =
    "\1\1\1\0\1\2\2\3\1\4\1\5\1\6\3\7"+
    "\1\10\1\11\1\12\1\13\1\14\1\15\1\16\1\17"+
    "\1\20\1\21\1\22\1\23\1\24\1\25\1\26\1\27"+
    "\15\6\1\30\1\31\1\32\1\4\1\5\1\10\1\11"+
    "\1\12\1\13\1\14\1\15\1\16\1\17\1\20\1\21"+
    "\1\22\1\23\1\24\1\25\1\26\1\27\15\31\1\33"+
    "\1\34\2\0\2\7\1\35\1\36\1\37\1\40\1\41"+
    "\1\42\1\43\1\44\14\6\1\45\6\6\1\35\1\36"+
    "\1\37\1\40\1\41\1\42\1\43\1\44\14\31\1\45"+
    "\6\31\1\46\1\47\2\50\2\0\2\7\4\6\1\51"+
    "\6\6\1\52\7\6\4\31\1\51\6\31\1\52\7\31"+
    "\1\0\2\7\1\6\1\53\2\6\1\54\3\6\1\55"+
    "\1\56\6\6\1\57\1\31\1\53\2\31\1\54\3\31"+
    "\1\55\1\56\6\31\1\57\2\7\3\6\1\60\1\6"+
    "\1\61\1\62\1\63\4\6\3\31\1\60\1\31\1\61"+
    "\1\62\1\63\4\31\2\7\3\6\1\64\1\65\2\6"+
    "\1\66\3\31\1\64\1\65\2\31\1\66\2\7\1\67"+
    "\1\70\2\6\1\71\1\67\1\70\2\31\1\71\2\7"+
    "\1\72\1\6\1\72\1\31\2\7\2\73\1\1";

  private static int [] zzUnpackAction() {
    int [] result = new int[284];
    int offset = 0;
    offset = zzUnpackAction(ZZ_ACTION_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAction(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /** 
   * Translates a state to a row index in the transition table
   */
  private static final int [] ZZ_ROWMAP = zzUnpackRowMap();

  private static final String ZZ_ROWMAP_PACKED_0 =
    "\0\0\0\67\0\156\0\245\0\156\0\334\0\156\0\u0113"+
    "\0\u014a\0\u0181\0\u01b8\0\156\0\156\0\156\0\156\0\156"+
    "\0\156\0\156\0\u01ef\0\u0226\0\u025d\0\u0294\0\u02cb\0\u0302"+
    "\0\156\0\u0339\0\u0370\0\u03a7\0\u03de\0\u0415\0\u044c\0\u0483"+
    "\0\u04ba\0\u04f1\0\u0528\0\u055f\0\u0596\0\u05cd\0\u0604\0\u063b"+
    "\0\156\0\u0672\0\156\0\u0672\0\u0672\0\u0672\0\u0672\0\u0672"+
    "\0\u0672\0\u0672\0\u0672\0\u0672\0\u06a9\0\u06e0\0\u0717\0\u074e"+
    "\0\u0785\0\u07bc\0\u0672\0\u07f3\0\u082a\0\u0861\0\u0898\0\u08cf"+
    "\0\u0906\0\u093d\0\u0974\0\u09ab\0\u09e2\0\u0a19\0\u0a50\0\u0a87"+
    "\0\u0abe\0\u0af5\0\156\0\u0b2c\0\u0b63\0\u0b9a\0\u0bd1\0\u0c08"+
    "\0\156\0\156\0\156\0\156\0\156\0\156\0\156\0\156"+
    "\0\u0c3f\0\u0c76\0\u0cad\0\u0ce4\0\u0d1b\0\u0d52\0\u0d89\0\u0dc0"+
    "\0\u0df7\0\u0e2e\0\u0e65\0\u0e9c\0\u0113\0\u0ed3\0\u0f0a\0\u0f41"+
    "\0\u0f78\0\u0faf\0\u0fe6\0\u0672\0\u0672\0\u0672\0\u0672\0\u0672"+
    "\0\u0672\0\u0672\0\u0672\0\u101d\0\u1054\0\u108b\0\u10c2\0\u10f9"+
    "\0\u1130\0\u1167\0\u119e\0\u11d5\0\u120c\0\u1243\0\u127a\0\u0672"+
    "\0\u12b1\0\u12e8\0\u131f\0\u1356\0\u138d\0\u13c4\0\156\0\156"+
    "\0\u13fb\0\156\0\u1432\0\u1469\0\u14a0\0\u14d7\0\u150e\0\u1545"+
    "\0\u157c\0\u15b3\0\u0113\0\u15ea\0\u1621\0\u1658\0\u168f\0\u16c6"+
    "\0\u16fd\0\u0113\0\u1734\0\u176b\0\u17a2\0\u17d9\0\u1810\0\u1847"+
    "\0\u187e\0\u18b5\0\u18ec\0\u1923\0\u195a\0\u0672\0\u1991\0\u19c8"+
    "\0\u19ff\0\u1a36\0\u1a6d\0\u1aa4\0\u0672\0\u1adb\0\u1b12\0\u1b49"+
    "\0\u1b80\0\u1bb7\0\u1bee\0\u1c25\0\u1c5c\0\u1c93\0\u1cca\0\u1d01"+
    "\0\u0113\0\u1d38\0\u1d6f\0\u0113\0\u1da6\0\u1ddd\0\u1e14\0\u0113"+
    "\0\u0113\0\u1e4b\0\u1e82\0\u1eb9\0\u1ef0\0\u1f27\0\u1f5e\0\u0113"+
    "\0\u1f95\0\u0672\0\u1fcc\0\u2003\0\u0672\0\u203a\0\u2071\0\u20a8"+
    "\0\u0672\0\u0672\0\u20df\0\u2116\0\u214d\0\u2184\0\u21bb\0\u21f2"+
    "\0\u0672\0\u2229\0\u2260\0\u2297\0\u22ce\0\u2305\0\u0113\0\u233c"+
    "\0\u0113\0\u0113\0\u0113\0\u2373\0\u23aa\0\u23e1\0\u2418\0\u244f"+
    "\0\u2486\0\u24bd\0\u0672\0\u24f4\0\u0672\0\u0672\0\u0672\0\u252b"+
    "\0\u2562\0\u2599\0\u25d0\0\u2607\0\u263e\0\u2675\0\u26ac\0\u26e3"+
    "\0\u0113\0\u0113\0\u271a\0\u2751\0\u0113\0\u2788\0\u27bf\0\u27f6"+
    "\0\u0672\0\u0672\0\u282d\0\u2864\0\u0672\0\u289b\0\u28d2\0\u0113"+
    "\0\u0113\0\u2909\0\u2940\0\u0113\0\u0672\0\u0672\0\u2977\0\u29ae"+
    "\0\u0672\0\u29e5\0\u2a1c\0\u0113\0\u2a53\0\u0672\0\u2a8a\0\u2ac1"+
    "\0\u2af8\0\u0113\0\u0672\0\u2ac1";

  private static int [] zzUnpackRowMap() {
    int [] result = new int[284];
    int offset = 0;
    offset = zzUnpackRowMap(ZZ_ROWMAP_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackRowMap(String packed, int offset, int [] result) {
    int i = 0;  /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int high = packed.charAt(i++) << 16;
      result[j++] = high | packed.charAt(i++);
    }
    return j;
  }

  /** 
   * The transition table of the DFA
   */
  private static final int [] ZZ_TRANS = zzUnpackTrans();

  private static final String ZZ_TRANS_PACKED_0 =
    "\1\3\1\4\2\5\1\6\1\7\1\10\1\11\1\3"+
    "\1\12\1\13\7\11\1\14\1\15\1\16\1\17\1\20"+
    "\1\21\1\22\1\23\1\24\1\25\1\26\1\27\1\30"+
    "\1\31\1\32\1\33\1\34\2\10\1\35\1\36\1\37"+
    "\1\40\1\41\1\10\1\42\1\10\1\43\1\44\1\45"+
    "\1\46\1\10\1\47\1\10\1\50\1\51\1\3\2\52"+
    "\1\53\1\52\1\54\1\55\14\52\1\56\1\57\1\60"+
    "\1\61\1\62\1\63\1\64\1\65\1\66\1\67\1\70"+
    "\1\71\1\72\1\73\1\74\1\75\1\76\2\52\1\77"+
    "\1\100\1\101\1\102\1\103\1\52\1\104\1\52\1\105"+
    "\1\106\1\107\1\110\1\52\1\111\1\52\1\112\1\113"+
    "\1\114\71\0\1\5\70\0\1\115\1\116\67\0\14\10"+
    "\20\0\23\10\11\0\1\117\1\0\11\117\54\0\1\117"+
    "\1\0\1\117\1\120\6\117\1\11\54\0\1\11\1\0"+
    "\11\11\76\0\1\121\66\0\1\122\66\0\1\123\66\0"+
    "\1\124\72\0\1\125\67\0\1\126\61\0\1\127\66\0"+
    "\1\130\43\0\14\10\20\0\1\10\1\131\21\10\10\0"+
    "\14\10\20\0\2\10\1\132\5\10\1\133\12\10\10\0"+
    "\14\10\20\0\1\134\22\10\10\0\14\10\20\0\3\10"+
    "\1\135\13\10\1\136\3\10\10\0\14\10\20\0\2\10"+
    "\1\137\20\10\10\0\14\10\20\0\11\10\1\140\5\10"+
    "\1\141\3\10\10\0\14\10\20\0\16\10\1\142\2\10"+
    "\1\143\1\10\10\0\14\10\20\0\5\10\1\144\6\10"+
    "\1\145\6\10\10\0\14\10\20\0\4\10\1\146\16\10"+
    "\10\0\14\10\20\0\21\10\1\147\1\10\10\0\14\10"+
    "\20\0\3\10\1\150\17\10\10\0\14\10\20\0\16\10"+
    "\1\151\1\152\3\10\10\0\14\10\20\0\1\10\1\153"+
    "\21\10\2\0\2\52\1\0\62\52\2\0\2\52\1\0"+
    "\26\52\1\154\33\52\2\0\2\52\1\0\26\52\1\155"+
    "\33\52\2\0\2\52\1\0\26\52\1\156\33\52\2\0"+
    "\2\52\1\0\26\52\1\157\33\52\2\0\2\52\1\0"+
    "\32\52\1\160\27\52\2\0\2\52\1\0\33\52\1\161"+
    "\26\52\2\0\2\52\1\0\26\52\1\162\33\52\2\0"+
    "\2\52\1\0\26\52\1\163\33\52\2\0\2\52\1\0"+
    "\40\52\1\164\21\52\2\0\2\52\1\0\41\52\1\165"+
    "\5\52\1\166\12\52\2\0\2\52\1\0\37\52\1\167"+
    "\22\52\2\0\2\52\1\0\42\52\1\170\13\52\1\171"+
    "\3\52\2\0\2\52\1\0\41\52\1\172\20\52\2\0"+
    "\2\52\1\0\50\52\1\173\5\52\1\174\3\52\2\0"+
    "\2\52\1\0\55\52\1\175\2\52\1\176\1\52\2\0"+
    "\2\52\1\0\44\52\1\177\6\52\1\200\6\52\2\0"+
    "\2\52\1\0\43\52\1\201\16\52\2\0\2\52\1\0"+
    "\60\52\1\202\1\52\2\0\2\52\1\0\42\52\1\203"+
    "\17\52\2\0\2\52\1\0\55\52\1\204\1\205\3\52"+
    "\2\0\2\52\1\0\40\52\1\206\21\52\51\0\1\207"+
    "\15\0\1\210\1\0\1\115\1\211\1\212\64\115\5\213"+
    "\1\214\61\213\7\0\1\215\1\0\11\215\54\0\1\215"+
    "\1\0\2\117\1\216\2\215\1\117\2\215\1\117\53\0"+
    "\14\10\20\0\1\10\1\217\21\10\10\0\14\10\20\0"+
    "\7\10\1\220\13\10\10\0\14\10\20\0\11\10\1\221"+
    "\11\10\10\0\14\10\20\0\7\10\1\222\13\10\10\0"+
    "\14\10\20\0\15\10\1\223\5\10\10\0\14\10\20\0"+
    "\2\10\1\224\20\10\10\0\14\10\20\0\4\10\1\225"+
    "\16\10\10\0\14\10\20\0\4\10\1\226\16\10\10\0"+
    "\14\10\20\0\20\10\1\227\2\10\10\0\14\10\20\0"+
    "\17\10\1\230\3\10\10\0\14\10\20\0\13\10\1\231"+
    "\7\10\10\0\14\10\20\0\11\10\1\232\11\10\10\0"+
    "\14\10\20\0\2\10\1\233\20\10\10\0\14\10\20\0"+
    "\13\10\1\234\7\10\10\0\14\10\20\0\11\10\1\235"+
    "\11\10\10\0\14\10\20\0\1\10\1\236\11\10\1\237"+
    "\7\10\10\0\14\10\20\0\1\240\22\10\10\0\14\10"+
    "\20\0\13\10\1\241\7\10\2\0\2\52\1\0\40\52"+
    "\1\242\21\52\2\0\2\52\1\0\46\52\1\243\13\52"+
    "\2\0\2\52\1\0\50\52\1\244\11\52\2\0\2\52"+
    "\1\0\46\52\1\245\13\52\2\0\2\52\1\0\54\52"+
    "\1\246\5\52\2\0\2\52\1\0\41\52\1\247\20\52"+
    "\2\0\2\52\1\0\43\52\1\250\16\52\2\0\2\52"+
    "\1\0\43\52\1\251\16\52\2\0\2\52\1\0\57\52"+
    "\1\252\2\52\2\0\2\52\1\0\56\52\1\253\3\52"+
    "\2\0\2\52\1\0\52\52\1\254\7\52\2\0\2\52"+
    "\1\0\50\52\1\255\11\52\2\0\2\52\1\0\41\52"+
    "\1\256\20\52\2\0\2\52\1\0\52\52\1\257\7\52"+
    "\2\0\2\52\1\0\50\52\1\260\11\52\2\0\2\52"+
    "\1\0\40\52\1\261\11\52\1\262\7\52\2\0\2\52"+
    "\1\0\37\52\1\263\22\52\2\0\2\52\1\0\52\52"+
    "\1\264\7\52\4\0\1\212\64\0\5\213\1\265\61\213"+
    "\4\0\1\212\1\214\70\0\1\266\1\0\11\266\54\0"+
    "\1\266\1\0\3\215\1\267\1\266\4\215\53\0\14\10"+
    "\20\0\2\10\1\270\20\10\10\0\14\10\20\0\3\10"+
    "\1\271\17\10\10\0\14\10\20\0\3\10\1\272\17\10"+
    "\10\0\14\10\20\0\11\10\1\273\11\10\10\0\14\10"+
    "\20\0\2\10\1\274\20\10\10\0\14\10\20\0\7\10"+
    "\1\275\13\10\10\0\14\10\20\0\11\10\1\276\11\10"+
    "\10\0\14\10\20\0\3\10\1\277\17\10\10\0\14\10"+
    "\20\0\3\10\1\300\17\10\10\0\14\10\20\0\7\10"+
    "\1\301\13\10\10\0\14\10\20\0\7\10\1\302\13\10"+
    "\10\0\14\10\20\0\2\10\1\303\20\10\10\0\14\10"+
    "\20\0\17\10\1\304\3\10\10\0\14\10\20\0\11\10"+
    "\1\305\11\10\10\0\14\10\20\0\22\10\1\306\10\0"+
    "\14\10\20\0\2\10\1\307\20\10\10\0\14\10\20\0"+
    "\12\10\1\310\10\10\2\0\2\52\1\0\41\52\1\311"+
    "\20\52\2\0\2\52\1\0\42\52\1\312\17\52\2\0"+
    "\2\52\1\0\42\52\1\313\17\52\2\0\2\52\1\0"+
    "\50\52\1\314\11\52\2\0\2\52\1\0\41\52\1\315"+
    "\20\52\2\0\2\52\1\0\46\52\1\316\13\52\2\0"+
    "\2\52\1\0\50\52\1\317\11\52\2\0\2\52\1\0"+
    "\42\52\1\320\17\52\2\0\2\52\1\0\42\52\1\321"+
    "\17\52\2\0\2\52\1\0\46\52\1\322\13\52\2\0"+
    "\2\52\1\0\46\52\1\323\13\52\2\0\2\52\1\0"+
    "\41\52\1\324\20\52\2\0\2\52\1\0\56\52\1\325"+
    "\3\52\2\0\2\52\1\0\50\52\1\326\11\52\2\0"+
    "\2\52\1\0\61\52\1\327\2\0\2\52\1\0\41\52"+
    "\1\330\20\52\2\0\2\52\1\0\51\52\1\331\10\52"+
    "\2\0\4\213\1\212\1\265\61\213\7\0\1\332\1\0"+
    "\11\332\54\0\1\332\1\0\2\266\1\333\2\332\1\266"+
    "\2\332\1\266\53\0\14\10\20\0\3\10\1\334\17\10"+
    "\10\0\14\10\20\0\5\10\1\335\15\10\10\0\14\10"+
    "\20\0\16\10\1\336\4\10\10\0\14\10\20\0\7\10"+
    "\1\337\13\10\10\0\14\10\20\0\13\10\1\340\7\10"+
    "\10\0\14\10\20\0\16\10\1\341\4\10\10\0\14\10"+
    "\20\0\3\10\1\342\17\10\10\0\14\10\20\0\3\10"+
    "\1\343\17\10\10\0\14\10\20\0\16\10\1\344\4\10"+
    "\10\0\14\10\20\0\3\10\1\345\17\10\10\0\14\10"+
    "\20\0\4\10\1\346\16\10\10\0\14\10\20\0\13\10"+
    "\1\347\7\10\2\0\2\52\1\0\42\52\1\350\17\52"+
    "\2\0\2\52\1\0\44\52\1\351\15\52\2\0\2\52"+
    "\1\0\55\52\1\352\4\52\2\0\2\52\1\0\46\52"+
    "\1\353\13\52\2\0\2\52\1\0\52\52\1\354\7\52"+
    "\2\0\2\52\1\0\55\52\1\355\4\52\2\0\2\52"+
    "\1\0\42\52\1\356\17\52\2\0\2\52\1\0\42\52"+
    "\1\357\17\52\2\0\2\52\1\0\55\52\1\360\4\52"+
    "\2\0\2\52\1\0\42\52\1\361\17\52\2\0\2\52"+
    "\1\0\43\52\1\362\16\52\2\0\2\52\1\0\52\52"+
    "\1\363\7\52\11\0\1\364\1\0\11\364\54\0\1\364"+
    "\1\0\4\332\1\365\4\332\53\0\14\10\20\0\4\10"+
    "\1\366\16\10\10\0\14\10\20\0\12\10\1\367\10\10"+
    "\10\0\14\10\20\0\4\10\1\370\16\10\10\0\14\10"+
    "\20\0\6\10\1\371\14\10\10\0\14\10\20\0\5\10"+
    "\1\372\15\10\10\0\14\10\20\0\6\10\1\373\14\10"+
    "\10\0\14\10\20\0\11\10\1\374\11\10\10\0\14\10"+
    "\20\0\6\10\1\375\14\10\2\0\2\52\1\0\43\52"+
    "\1\376\16\52\2\0\2\52\1\0\51\52\1\377\10\52"+
    "\2\0\2\52\1\0\43\52\1\u0100\16\52\2\0\2\52"+
    "\1\0\45\52\1\u0101\14\52\2\0\2\52\1\0\44\52"+
    "\1\u0102\15\52\2\0\2\52\1\0\45\52\1\u0103\14\52"+
    "\2\0\2\52\1\0\50\52\1\u0104\11\52\2\0\2\52"+
    "\1\0\45\52\1\u0105\14\52\11\0\1\u0106\1\0\11\u0106"+
    "\54\0\1\u0106\1\0\2\364\3\u0106\1\u0107\2\u0106\1\364"+
    "\53\0\14\10\20\0\5\10\1\u0108\15\10\10\0\14\10"+
    "\20\0\7\10\1\u0109\13\10\10\0\14\10\20\0\6\10"+
    "\1\u010a\14\10\10\0\14\10\20\0\11\10\1\u010b\11\10"+
    "\10\0\14\10\20\0\3\10\1\u010c\17\10\2\0\2\52"+
    "\1\0\44\52\1\u010d\15\52\2\0\2\52\1\0\46\52"+
    "\1\u010e\13\52\2\0\2\52\1\0\45\52\1\u010f\14\52"+
    "\2\0\2\52\1\0\50\52\1\u0110\11\52\2\0\2\52"+
    "\1\0\42\52\1\u0111\17\52\11\0\1\u0112\1\0\11\u0112"+
    "\54\0\1\u0112\1\0\3\u0106\2\u0112\1\u0106\1\u0113\2\u0106"+
    "\53\0\14\10\20\0\11\10\1\u0114\11\10\10\0\14\10"+
    "\20\0\3\10\1\u0115\17\10\2\0\2\52\1\0\50\52"+
    "\1\u0116\11\52\2\0\2\52\1\0\42\52\1\u0117\17\52"+
    "\11\0\1\u0118\1\0\11\u0118\54\0\1\u0118\1\0\2\u0112"+
    "\1\u0119\2\u0118\1\u0112\2\u0118\1\u0112\53\0\14\10\20\0"+
    "\12\10\1\u011a\10\10\2\0\2\52\1\0\51\52\1\u011b"+
    "\10\52\11\0\1\u011c\1\0\11\u011c\54\0\1\u011c\1\0"+
    "\4\u0118\1\u011c\4\u0118\45\0";

  private static int [] zzUnpackTrans() {
    int [] result = new int[11055];
    int offset = 0;
    offset = zzUnpackTrans(ZZ_TRANS_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackTrans(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      value--;
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /* error codes */
  private static final int ZZ_UNKNOWN_ERROR = 0;
  private static final int ZZ_NO_MATCH = 1;
  private static final int ZZ_PUSHBACK_2BIG = 2;

  /* error messages for the codes above */
  private static final String ZZ_ERROR_MSG[] = {
    "Unkown internal scanner error",
    "Error: could not match input",
    "Error: pushback value was too large"
  };

  /**
   * ZZ_ATTRIBUTE[aState] contains the attributes of state <code>aState</code>
   */
  private static final int [] ZZ_ATTRIBUTE = zzUnpackAttribute();

  private static final String ZZ_ATTRIBUTE_PACKED_0 =
    "\1\1\1\0\1\11\1\1\1\11\1\1\1\11\4\1"+
    "\7\11\6\1\1\11\17\1\1\11\1\1\1\11\37\1"+
    "\1\11\1\1\2\0\2\1\10\11\56\1\2\11\1\1"+
    "\1\11\2\0\50\1\1\0\147\1";

  private static int [] zzUnpackAttribute() {
    int [] result = new int[284];
    int offset = 0;
    offset = zzUnpackAttribute(ZZ_ATTRIBUTE_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAttribute(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }

  /** the input device */
  private java.io.Reader zzReader;

  /** the current state of the DFA */
  private int zzState;

  /** the current lexical state */
  private int zzLexicalState = YYINITIAL;

  /** this buffer contains the current text to be matched and is
      the source of the yytext() string */
  private char zzBuffer[] = new char[ZZ_BUFFERSIZE];

  /** the textposition at the last accepting state */
  private int zzMarkedPos;

  /** the current text position in the buffer */
  private int zzCurrentPos;

  /** startRead marks the beginning of the yytext() string in the buffer */
  private int zzStartRead;

  /** endRead marks the last character in the buffer, that has been read
      from input */
  private int zzEndRead;

  /** number of newlines encountered up to the start of the matched text */
  private int yyline;

  /** the number of characters up to the start of the matched text */
  private int yychar;

  /**
   * the number of characters from the last newline up to the start of the 
   * matched text
   */
  private int yycolumn;

  /** 
   * zzAtBOL == true <=> the scanner is currently at the beginning of a line
   */
  private boolean zzAtBOL = true;

  /** zzAtEOF == true <=> the scanner is at the EOF */
  private boolean zzAtEOF;

  /* user code: */

    StringBuffer string = new StringBuffer();

    int ENDINPUT = 0;
    int BOOLEAN = 1;
    int CAND = 2;
    int CLASS = 3;
    int COR = 4;
    int ELSE = 5;
    int EQEQ = 6;
    int EXTENDS = 7;
    int FALSE = 8;
    int IDENT = 9;
    int IF = 10;
    int INT = 11;
    int INTLIT = 12;
    int NEQ = 13;
    int NEW = 14;
    int NULL = 15;
    int RETURN = 16;
    int STATIC = 17;
    int SUPER = 18;
    int THIS = 19;
    int TRUE = 20;
    int VOID = 21;
    int WHILE = 22;
    int GTEQ = 23;
    int LTEQ = 24;
    int PLUSEQ = 25;
    int MINUSEQ = 26;
    int PRIVATE = 27;
    int PROTECTED = 28;
    int PUBLIC = 29;
    int ABSTRACT = 30;
    int STRLIT = 31;
    // '!' (code=33)
    // '&' (code=38)
    // '(' (code=40)
    // ')' (code=41)
    // '*' (code=42)
    // '+' (code=43)
    // ',' (code=44)
    // '-' (code=45)
    // '.' (code=46)
    // '/' (code=47)
    // ';' (code=59)
    // '<' (code=60)
    // '=' (code=61)
    // '>' (code=62)
    // '^' (code=94)
    // '{' (code=123)
    // '|' (code=124)
    // '}' (code=125)



  /**
   * Creates a new scanner
   * There is also a java.io.InputStream version of this constructor.
   *
   * @param   in  the java.io.Reader to read input from.
   */
  public Lexer(java.io.Reader in) {
    this.zzReader = in;
  }

  /**
   * Creates a new scanner.
   * There is also java.io.Reader version of this constructor.
   *
   * @param   in  the java.io.Inputstream to read input from.
   */
  public Lexer(java.io.InputStream in) {
    this(new java.io.InputStreamReader(in));
  }

  /** 
   * Unpacks the compressed character translation table.
   *
   * @param packed   the packed character translation table
   * @return         the unpacked character translation table
   */
  private static char [] zzUnpackCMap(String packed) {
    char [] map = new char[0x10000];
    int i = 0;  /* index in packed string  */
    int j = 0;  /* index in unpacked array */
    while (i < 1786) {
      int  count = packed.charAt(i++);
      char value = packed.charAt(i++);
      do map[j++] = value; while (--count > 0);
    }
    return map;
  }


  /**
   * Refills the input buffer.
   *
   * @return      <code>false</code>, iff there was new input.
   * 
   * @exception   java.io.IOException  if any I/O-Error occurs
   */
  private boolean zzRefill() throws java.io.IOException {

    /* first: make room (if you can) */
    if (zzStartRead > 0) {
      System.arraycopy(zzBuffer, zzStartRead,
                       zzBuffer, 0,
                       zzEndRead-zzStartRead);

      /* translate stored positions */
      zzEndRead-= zzStartRead;
      zzCurrentPos-= zzStartRead;
      zzMarkedPos-= zzStartRead;
      zzStartRead = 0;
    }

    /* is the buffer big enough? */
    if (zzCurrentPos >= zzBuffer.length) {
      /* if not: blow it up */
      char newBuffer[] = new char[zzCurrentPos*2];
      System.arraycopy(zzBuffer, 0, newBuffer, 0, zzBuffer.length);
      zzBuffer = newBuffer;
    }

    /* finally: fill the buffer with new input */
    int numRead = zzReader.read(zzBuffer, zzEndRead,
                                            zzBuffer.length-zzEndRead);

    if (numRead > 0) {
      zzEndRead+= numRead;
      return false;
    }
    // unlikely but not impossible: read 0 characters, but not at end of stream    
    if (numRead == 0) {
      int c = zzReader.read();
      if (c == -1) {
        return true;
      } else {
        zzBuffer[zzEndRead++] = (char) c;
        return false;
      }     
    }

	// numRead < 0
    return true;
  }

    
  /**
   * Closes the input stream.
   */
  public final void yyclose() throws java.io.IOException {
    zzAtEOF = true;            /* indicate end of file */
    zzEndRead = zzStartRead;  /* invalidate buffer    */

    if (zzReader != null)
      zzReader.close();
  }


  /**
   * Resets the scanner to read from a new input stream.
   * Does not close the old reader.
   *
   * All internal variables are reset, the old input stream 
   * <b>cannot</b> be reused (internal buffer is discarded and lost).
   * Lexical state is set to <tt>ZZ_INITIAL</tt>.
   *
   * @param reader   the new input stream 
   */
  public final void yyreset(java.io.Reader reader) {
    zzReader = reader;
    zzAtBOL  = true;
    zzAtEOF  = false;
    zzEndRead = zzStartRead = 0;
    zzCurrentPos = zzMarkedPos = 0;
    yyline = yychar = yycolumn = 0;
    zzLexicalState = YYINITIAL;
  }


  /**
   * Returns the current lexical state.
   */
  public final int yystate() {
    return zzLexicalState;
  }


  /**
   * Enters a new lexical state
   *
   * @param newState the new lexical state
   */
  public final void yybegin(int newState) {
    zzLexicalState = newState;
  }


  /**
   * Returns the text matched by the current regular expression.
   */
  public final String yytext() {
    return new String( zzBuffer, zzStartRead, zzMarkedPos-zzStartRead );
  }


  /**
   * Returns the character at position <tt>pos</tt> from the 
   * matched text. 
   * 
   * It is equivalent to yytext().charAt(pos), but faster
   *
   * @param pos the position of the character to fetch. 
   *            A value from 0 to yylength()-1.
   *
   * @return the character at position pos
   */
  public final char yycharat(int pos) {
    return zzBuffer[zzStartRead+pos];
  }


  /**
   * Returns the length of the matched text region.
   */
  public final int yylength() {
    return zzMarkedPos-zzStartRead;
  }


  /**
   * Reports an error that occured while scanning.
   *
   * In a wellformed scanner (no or only correct usage of 
   * yypushback(int) and a match-all fallback rule) this method 
   * will only be called with things that "Can't Possibly Happen".
   * If this method is called, something is seriously wrong
   * (e.g. a JFlex bug producing a faulty scanner etc.).
   *
   * Usual syntax/scanner level error handling should be done
   * in error fallback rules.
   *
   * @param   errorCode  the code of the errormessage to display
   */
  private void zzScanError(int errorCode) {
    String message;
    try {
      message = ZZ_ERROR_MSG[errorCode];
    }
    catch (ArrayIndexOutOfBoundsException e) {
      message = ZZ_ERROR_MSG[ZZ_UNKNOWN_ERROR];
    }

    throw new Error(message);
  } 


  /**
   * Pushes the specified amount of characters back into the input stream.
   *
   * They will be read again by then next call of the scanning method
   *
   * @param number  the number of characters to be read again.
   *                This number must not be greater than yylength()!
   */
  public void yypushback(int number)  {
    if ( number > yylength() )
      zzScanError(ZZ_PUSHBACK_2BIG);

    zzMarkedPos -= number;
  }


  /**
   * Resumes scanning until the next regular expression is matched,
   * the end of input is encountered or an I/O-Error occurs.
   *
   * @return      the next token
   * @exception   java.io.IOException  if any I/O-Error occurs
   */
  public int yylex() throws java.io.IOException {
    int zzInput;
    int zzAction;

    // cached fields:
    int zzCurrentPosL;
    int zzMarkedPosL;
    int zzEndReadL = zzEndRead;
    char [] zzBufferL = zzBuffer;
    char [] zzCMapL = ZZ_CMAP;

    int [] zzTransL = ZZ_TRANS;
    int [] zzRowMapL = ZZ_ROWMAP;
    int [] zzAttrL = ZZ_ATTRIBUTE;

    while (true) {
      zzMarkedPosL = zzMarkedPos;

      boolean zzR = false;
      for (zzCurrentPosL = zzStartRead; zzCurrentPosL < zzMarkedPosL;
                                                             zzCurrentPosL++) {
        switch (zzBufferL[zzCurrentPosL]) {
        case '\u000B':
        case '\u000C':
        case '\u0085':
        case '\u2028':
        case '\u2029':
          yyline++;
          yycolumn = 0;
          zzR = false;
          break;
        case '\r':
          yyline++;
          yycolumn = 0;
          zzR = true;
          break;
        case '\n':
          if (zzR)
            zzR = false;
          else {
            yyline++;
            yycolumn = 0;
          }
          break;
        default:
          zzR = false;
          yycolumn++;
        }
      }

      if (zzR) {
        // peek one character ahead if it is \n (if we have counted one line too much)
        boolean zzPeek;
        if (zzMarkedPosL < zzEndReadL)
          zzPeek = zzBufferL[zzMarkedPosL] == '\n';
        else if (zzAtEOF)
          zzPeek = false;
        else {
          boolean eof = zzRefill();
          zzEndReadL = zzEndRead;
          zzMarkedPosL = zzMarkedPos;
          zzBufferL = zzBuffer;
          if (eof) 
            zzPeek = false;
          else 
            zzPeek = zzBufferL[zzMarkedPosL] == '\n';
        }
        if (zzPeek) yyline--;
      }
      zzAction = -1;

      zzCurrentPosL = zzCurrentPos = zzStartRead = zzMarkedPosL;
  
      zzState = ZZ_LEXSTATE[zzLexicalState];


      zzForAction: {
        while (true) {
    
          if (zzCurrentPosL < zzEndReadL)
            zzInput = zzBufferL[zzCurrentPosL++];
          else if (zzAtEOF) {
            zzInput = YYEOF;
            break zzForAction;
          }
          else {
            // store back cached positions
            zzCurrentPos  = zzCurrentPosL;
            zzMarkedPos   = zzMarkedPosL;
            boolean eof = zzRefill();
            // get translated positions and possibly new buffer
            zzCurrentPosL  = zzCurrentPos;
            zzMarkedPosL   = zzMarkedPos;
            zzBufferL      = zzBuffer;
            zzEndReadL     = zzEndRead;
            if (eof) {
              zzInput = YYEOF;
              break zzForAction;
            }
            else {
              zzInput = zzBufferL[zzCurrentPosL++];
            }
          }
          int zzNext = zzTransL[ zzRowMapL[zzState] + zzCMapL[zzInput] ];
          if (zzNext == -1) break zzForAction;
          zzState = zzNext;

          int zzAttributes = zzAttrL[zzState];
          if ( (zzAttributes & 1) == 1 ) {
            zzAction = zzState;
            zzMarkedPosL = zzCurrentPosL;
            if ( (zzAttributes & 8) == 8 ) break zzForAction;
          }

        }
      }

      // store back cached position
      zzMarkedPos = zzMarkedPosL;

      switch (zzAction < 0 ? zzAction : ZZ_ACTION[zzAction]) {
        case 3: 
          { /* ignore whitespace */
          }
        case 60: break;
        case 37: 
          { return IF;
          }
        case 61: break;
        case 55: 
          { return BOOLEAN;
          }
        case 62: break;
        case 10: 
          { return '{';
          }
        case 63: break;
        case 23: 
          { return '-';
          }
        case 64: break;
        case 16: 
          { return '>';
          }
        case 65: break;
        case 27: 
          { yybegin(YYINITIAL); return STRLIT;
          }
        case 66: break;
        case 30: 
          { return GTEQ;
          }
        case 67: break;
        case 24: 
          { string.setLength(0); yybegin(STRING);
          }
        case 68: break;
        case 13: 
          { return ',';
          }
        case 69: break;
        case 36: 
          { return MINUSEQ;
          }
        case 70: break;
        case 15: 
          { return '=';
          }
        case 71: break;
        case 59: 
          { return PROTECTED;
          }
        case 72: break;
        case 2: 
          { System.out.println("Illegal char, '" + yytext() +
                   "' line: " + yyline + ", column: " + yychar);
          }
        case 73: break;
        case 28: 
          { string.append('\\');
          }
        case 74: break;
        case 50: 
          { return FALSE;
          }
        case 75: break;
        case 22: 
          { return '+';
          }
        case 76: break;
        case 17: 
          { return '<';
          }
        case 77: break;
        case 26: 
          { System.out.print(yytext());
          }
        case 78: break;
        case 57: 
          { return PRIVATE;
          }
        case 79: break;
        case 21: 
          { return '^';
          }
        case 80: break;
        case 5: 
          { return '*';
          }
        case 81: break;
        case 12: 
          { return ';';
          }
        case 82: break;
        case 44: 
          { return NULL;
          }
        case 83: break;
        case 18: 
          { return '!';
          }
        case 84: break;
        case 29: 
          { return EQEQ;
          }
        case 85: break;
        case 39: 
          { string.append('\"');
          }
        case 86: break;
        case 56: 
          { return EXTENDS;
          }
        case 87: break;
        case 42: 
          { return INT;
          }
        case 88: break;
        case 9: 
          { return ')';
          }
        case 89: break;
        case 46: 
          { return THIS;
          }
        case 90: break;
        case 49: 
          { return SUPER;
          }
        case 91: break;
        case 32: 
          { return NEQ;
          }
        case 92: break;
        case 34: 
          { return COR;
          }
        case 93: break;
        case 41: 
          { return NEW;
          }
        case 94: break;
        case 33: 
          { return CAND;
          }
        case 95: break;
        case 8: 
          { return '(';
          }
        case 96: break;
        case 48: 
          { return CLASS;
          }
        case 97: break;
        case 38: 
          { string.append('\n');
          }
        case 98: break;
        case 43: 
          { return ELSE;
          }
        case 99: break;
        case 53: 
          { return RETURN;
          }
        case 100: break;
        case 7: 
          { return INTLIT;
          }
        case 101: break;
        case 51: 
          { return WHILE;
          }
        case 102: break;
        case 35: 
          { return PLUSEQ;
          }
        case 103: break;
        case 47: 
          { return VOID;
          }
        case 104: break;
        case 40: 
          { /* throw away comments */
          }
        case 105: break;
        case 31: 
          { return LTEQ;
          }
        case 106: break;
        case 11: 
          { return '}';
          }
        case 107: break;
        case 54: 
          { return PUBLIC;
          }
        case 108: break;
        case 45: 
          { return TRUE;
          }
        case 109: break;
        case 6: 
          { return IDENT;
          }
        case 110: break;
        case 4: 
          { return '/';
          }
        case 111: break;
        case 52: 
          { return STATIC;
          }
        case 112: break;
        case 58: 
          { return ABSTRACT;
          }
        case 113: break;
        case 19: 
          { return '&';
          }
        case 114: break;
        case 1: 
          { System.out.println("rejecting number larger than MAXINT: " + yytext() + " --\n");
          }
        case 115: break;
        case 20: 
          { return '|';
          }
        case 116: break;
        case 25: 
          { string.append( yytext() );
          }
        case 117: break;
        case 14: 
          { return '.';
          }
        case 118: break;
        default: 
          if (zzInput == YYEOF && zzStartRead == zzCurrentPos) {
            zzAtEOF = true;
            return YYEOF;
          } 
          else {
            zzScanError(ZZ_NO_MATCH);
          }
      }
    }
  }

  /**
   * Runs the scanner on input files.
   *
   * This is a standalone scanner, it will print any unmatched
   * text to System.out unchanged.
   *
   * @param argv   the command line, contains the filenames to run
   *               the scanner on.
   */
  public static void main(String argv[]) {
    if (argv.length == 0) {
      System.out.println("Usage : java Lexer <inputfile>");
    }
    else {
      for (int i = 0; i < argv.length; i++) {
        Lexer scanner = null;
        try {
          scanner = new Lexer( new java.io.FileReader(argv[i]) );
          while ( !scanner.zzAtEOF ) scanner.yylex();
        }
        catch (java.io.FileNotFoundException e) {
          System.out.println("File not found : \""+argv[i]+"\"");
        }
        catch (java.io.IOException e) {
          System.out.println("IO error scanning file \""+argv[i]+"\"");
          System.out.println(e);
        }
        catch (Exception e) {
          System.out.println("Unexpected exception:");
          e.printStackTrace();
        }
      }
    }
  }


}
